# Generated by Django 4.1.2 on 2022-10-24 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.TimeField(default=datetime.datetime(2022, 10, 24, 21, 12, 20, 530098)),
        ),
    ]
